name: Feature Request
description: Suggest a new feature or enhancement (bold ideas welcome)
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! New ideas keep the gears turning. Please describe your idea below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing feature requests (no need to reinvent the broom)
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Thaumic Cast would this affect?
      options:
        - Desktop App
        - Chrome Extension
        - Headless Server
        - Core Library
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution (even if it sounds like magic)
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered (even odd ones)?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or mockups (diagrams welcome)
